"""Masked panel inpainting — produces the photoreal "after" frame by
painting solar panels ONLY inside a roof mask, then compositing the
result back over the untouched "before" image.

Why this service exists
-----------------------

The previous "after" frame was generated by an unmasked image edit
(``ai_panel_paint_service`` → nano-banana). A free-form generative
model re-imagines the whole frame: it silently re-crops, re-zooms and
re-frames the photo, so the before/after pair was never pixel-aligned
and the transition video "jumped".

The masked pipeline removes that failure mode by construction:

    Google Solar API  →  panel geometry
                          ↓
    solar_rendering_service.render_before_and_mask()
        → before.png            (real aerial crop, no panels)
        → mask.png              (white = panel footprints, black else)
                          ↓
    FLUX Fill inpaint  (paints panels ONLY inside the white mask)
                          ↓
    composite_inside_mask(before, inpainted, mask)
        → after.png = before, byte-identical outside the mask,
          photoreal panels inside it
                          ↓
    crossfade sidecar  (perfectly aligned wipe reveal)

Because the final composite pastes the model's output only where the
mask is white, every pixel outside the roof is guaranteed identical to
the before image — alignment is no longer at the mercy of the model.

Override points (env)
---------------------

``REPLICATE_API_TOKEN``          — required
``INPAINT_MODEL_OWNER``          — defaults to ``black-forest-labs``
``INPAINT_MODEL_NAME``           — defaults to ``flux-fill-pro``
"""

from __future__ import annotations

import asyncio
import contextlib
import io
import os
from typing import Any

import httpx
from PIL import Image
from tenacity import retry, stop_after_attempt, wait_exponential

from ..core.config import settings
from ..core.logging import get_logger

log = get_logger(__name__)


REPLICATE_API_BASE = "https://api.replicate.com/v1"

# Env-overridable so the inpaint engine can be swapped without a redeploy.
DEFAULT_MODEL_OWNER = os.getenv("INPAINT_MODEL_OWNER", "black-forest-labs")
DEFAULT_MODEL_NAME = os.getenv("INPAINT_MODEL_NAME", "flux-fill-pro")

_PREDICTIONS_URL_FMT = REPLICATE_API_BASE + "/models/{owner}/{name}/predictions"
_PREDICTION_URL_FMT = REPLICATE_API_BASE + "/predictions/{pred_id}"


class InpaintError(Exception):
    """Raised when the masked inpaint call fails to return a usable image."""


# ---------------------------------------------------------------------------
# Prompt construction (pure)
# ---------------------------------------------------------------------------


def build_inpaint_prompt(*, panel_count: int, kwp: float | None = None) -> str:
    """Compose the FLUX Fill prompt.

    The mask already constrains WHERE panels go, so — unlike the
    unmasked nano-banana prompt — this only has to describe WHAT to
    paint inside the masked region: the panel material, layout and
    lighting. No "do not touch the lawn" guardrails are needed.
    """
    scale = f" forming roughly a {kwp:.0f} kWp array" if kwp and kwp > 0 else ""
    count = f"approximately {panel_count} " if panel_count > 0 else ""
    return (
        f"Photorealistic dark monocrystalline silicon solar panels, "
        f"{count}rectangular modules with thin silver aluminium frames, "
        "installed in neat parallel rows aligned with the roof edges"
        f"{scale}. The panels lie flat on the rooftop, follow its exact "
        "perspective and slope, and match the natural daylight "
        "direction, shadows and resolution of the surrounding aerial "
        "photograph. Top-down aerial view, sharp focus, no text."
    )


# ---------------------------------------------------------------------------
# Compositing (pure)
# ---------------------------------------------------------------------------


def composite_inside_mask(
    before_bytes: bytes,
    inpainted_bytes: bytes,
    mask_bytes: bytes,
) -> bytes:
    """Paste the inpainted pixels onto ``before`` only inside the mask.

    Returns a PNG where every pixel is the inpainted output where the
    mask is white, the original before pixel where the mask is black,
    and a feathered blend along the mask edge. This is what guarantees
    the after frame is pixel-aligned with the before frame: the model
    output is used *exclusively* inside the roof mask.
    """
    before = Image.open(io.BytesIO(before_bytes)).convert("RGB")
    inpainted = Image.open(io.BytesIO(inpainted_bytes)).convert("RGB")
    mask = Image.open(io.BytesIO(mask_bytes)).convert("L")

    # The model may emit a different resolution; bring both the
    # inpainted output and the mask back onto the before canvas.
    if inpainted.size != before.size:
        inpainted = inpainted.resize(before.size, Image.LANCZOS)
    if mask.size != before.size:
        mask = mask.resize(before.size, Image.LANCZOS)

    composited = Image.composite(inpainted, before, mask)
    buf = io.BytesIO()
    composited.save(buf, format="PNG", optimize=True, compress_level=6)
    return buf.getvalue()


# ---------------------------------------------------------------------------
# HTTP / Replicate plumbing
# ---------------------------------------------------------------------------


def _auth_headers() -> dict[str, str]:
    if not settings.replicate_api_token:
        raise InpaintError("REPLICATE_API_TOKEN not configured")
    return {
        "Authorization": f"Bearer {settings.replicate_api_token}",
        "Content-Type": "application/json",
    }


def _extract_output_url(output: Any) -> str | None:
    """FLUX Fill returns either a URL string or a list of URL strings."""
    if isinstance(output, str) and output.startswith("http"):
        return output
    if isinstance(output, list) and output:
        first = output[0]
        if isinstance(first, str) and first.startswith("http"):
            return first
    return None


@retry(
    stop=stop_after_attempt(3),
    wait=wait_exponential(multiplier=1, min=2, max=10),
    reraise=True,
)
async def inpaint_panels(
    *,
    before_image_url: str,
    mask_image_url: str,
    prompt: str,
    poll_timeout_s: float = 120.0,
    poll_interval_s: float = 2.0,
    http_client: httpx.AsyncClient | None = None,
    model_owner: str | None = None,
    model_name: str | None = None,
) -> bytes:
    """Run masked inpainting, return the raw PNG bytes of the result.

    The caller composites the output back over the before image via
    :func:`composite_inside_mask`, so this function only has to deliver
    the model's raw render.
    """
    owner = model_owner or DEFAULT_MODEL_OWNER
    name = model_name or DEFAULT_MODEL_NAME
    create_url = _PREDICTIONS_URL_FMT.format(owner=owner, name=name)

    payload = {
        "input": {
            "prompt": prompt,
            "image": before_image_url,
            "mask": mask_image_url,
            "output_format": "png",
        }
    }

    log.info(
        "inpaint.start",
        before_url_peek=before_image_url[:100],
        mask_url_peek=mask_image_url[:100],
        model=f"{owner}/{name}",
    )

    owns_client = http_client is None
    client = http_client or httpx.AsyncClient(
        timeout=httpx.Timeout(connect=10.0, read=60.0, write=60.0, pool=60.0)
    )

    try:
        resp = await client.post(
            create_url,
            headers={**_auth_headers(), "Prefer": "wait=10"},
            json=payload,
        )
        # 429 = rate-limit; honour Retry-After then retry once in-process.
        if resp.status_code == 429:
            retry_after_s = 30.0
            ra_header = resp.headers.get("Retry-After")
            if ra_header:
                with contextlib.suppress(ValueError):
                    retry_after_s = float(ra_header)
            log.warning("inpaint.rate_limited", retry_after_s=retry_after_s)
            await asyncio.sleep(min(retry_after_s, 60.0))
            resp = await client.post(
                create_url,
                headers={**_auth_headers(), "Prefer": "wait=10"},
                json=payload,
            )
        if resp.status_code >= 400:
            raise InpaintError(f"create status={resp.status_code} body={resp.text[:300]}")

        body = resp.json()
        pred_id = body.get("id")
        status = body.get("status", "")
        output = body.get("output")
        error = body.get("error")

        deadline = asyncio.get_event_loop().time() + poll_timeout_s
        while status not in ("succeeded", "failed", "canceled"):
            if asyncio.get_event_loop().time() > deadline:
                raise InpaintError(f"prediction {pred_id} timed out")
            await asyncio.sleep(poll_interval_s)
            r = await client.get(
                _PREDICTION_URL_FMT.format(pred_id=pred_id),
                headers=_auth_headers(),
            )
            if r.status_code >= 400:
                raise InpaintError(f"poll {pred_id} status={r.status_code} body={r.text[:200]}")
            j = r.json()
            status = j.get("status", "")
            output = j.get("output")
            error = j.get("error")

        if status != "succeeded":
            raise InpaintError(f"prediction {pred_id} ended {status}: {error or 'unknown'}")

        out_url = _extract_output_url(output)
        if not out_url:
            raise InpaintError(f"no output URL in response (output={output!r})")

        dl = await client.get(out_url, timeout=60.0)
        if dl.status_code != 200:
            raise InpaintError(f"download {out_url[:80]} status={dl.status_code}")

        log.info("inpaint.done", prediction_id=pred_id, output_kb=len(dl.content) // 1024)
        return dl.content

    finally:
        if owns_client:
            await client.aclose()
