-- ============================================================
-- 0073 — acquisition_campaigns.custom_copy_override
-- ============================================================
--
-- Adds a per-campaign manual copy override for the 4 dynamic
-- email-template variables wired by Sprint 9 Fase A/B.
--
-- Use case ("campagna straordinaria"):
--   The operator runs the prospector at /scoperta, finds a
--   targeted list (e.g. amministratori di condominio ATECO 68.32),
--   creates a dedicated acquisition_campaign, and wants to ship
--   *hand-written* copy that emphasises a specific angle
--   (e.g. tecnico-impattante for condo administrators).
--
-- Without this column the OutreachAgent always falls back to
-- the cluster A/B engine (auto-generated by Claude Haiku).
-- The cluster engine is great for steady-state automation but
-- gives no way to express "for THIS campaign, use exactly THIS
-- subject + opening + proposition + CTA, period".
--
-- Column shape (JSONB, nullable):
--   {
--     "enabled": true,
--     "copy_subject":         "...",
--     "copy_opening_line":    "...",
--     "copy_proposition_line":"...",
--     "cta_primary_label":    "..."
--   }
--
-- Semantics in OutreachAgent:
--   1. If campaign.custom_copy_override.enabled = true → use these
--      4 fields directly, skip cluster A/B variant lookup.
--   2. Else → existing behaviour (cluster A/B 50/50, fallback
--      to default Jinja copy if no variants are ready).
--
-- The column is intentionally a single JSONB blob (not 4 columns)
-- because it lets new copy keys (e.g. cta_secondary_label) be added
-- in one place without an ALTER TABLE per field.
--
-- NULL == no override == default cluster A/B behaviour.

BEGIN;

ALTER TABLE acquisition_campaigns
    ADD COLUMN IF NOT EXISTS custom_copy_override JSONB DEFAULT NULL;

COMMENT ON COLUMN acquisition_campaigns.custom_copy_override IS
    'Optional manual copy override (JSONB with keys: enabled, '
    'copy_subject, copy_opening_line, copy_proposition_line, '
    'cta_primary_label). When enabled=true the OutreachAgent '
    'bypasses the cluster A/B engine and uses these 4 fields.';

COMMIT;
